export const paymentsContractABI = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_adminManagementCoreContractAddress',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'OperatorCore__AccessDenied_AdminOnly', type: 'error' },
  { inputs: [], name: 'OperatorCore__NonMatchingAdminAddress', type: 'error' },
  { inputs: [], name: 'OperatorCore__ZeroAddressError', type: 'error' },
  { inputs: [], name: 'OperatorCore__ZeroTokenDecimalsError', type: 'error' },
  { inputs: [], name: 'Operator__AccessDenied_AdminOnly', type: 'error' },
  { inputs: [], name: 'Operator__ZeroAddressError', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'string',
        name: 'message',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'string',
        name: 'contractName',
        type: 'string',
      },
    ],
    name: 'Logs',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'sender',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'receiver',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'string',
        name: 'tokenType',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'totalAmount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'commision',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountSent',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'sendTime',
        type: 'uint256',
      },
    ],
    name: 'TransferProcessed',
    type: 'event',
  },
  {
    inputs: [],
    name: 'getAdminManagementCoreContractAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractName',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getERC20TokenAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getERC20TokenDecimals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
    name: 'handleApproveERC20Transfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_createdBy', type: 'address' },
      { internalType: 'uint256', name: '_totalAmount', type: 'uint256' },
      { internalType: 'address', name: '_receiverAddress', type: 'address' },
    ],
    name: 'handleTransfer__ERC20',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ping',
    outputs: [
      { internalType: 'string', name: '', type: 'string' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address payable',
        name: '_receiverAddress',
        type: 'address',
      },
    ],
    name: 'sendEther__PassThrough',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newAddress', type: 'address' }],
    name: 'updateAdminManagementCoreContractAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_tokenAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenDecimals', type: 'uint256' },
    ],
    name: 'updateERC20TokenData',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
