export const USDLContractABI = [
  {
    inputs: [
      { internalType: 'string', name: '_tokenName', type: 'string' },
      { internalType: 'string', name: '_tokenLogoCID', type: 'string' },
      { internalType: 'string', name: '_tokenMetadataCID', type: 'string' },
      { internalType: 'string', name: '_tokenSymbol', type: 'string' },
      { internalType: 'uint8', name: '_decimals', type: 'uint8' },
      { internalType: 'uint256', name: '_supply', type: 'uint256' },
      {
        internalType: 'address',
        name: '_adminManagementCoreContractAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_proposalManagementCoreContractAddress',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'LolaUSDCore__AccessDenied_AdminOnly', type: 'error' },
  { inputs: [], name: 'LolaUSDCore__LogoNameCannotBeEmpty', type: 'error' },
  { inputs: [], name: 'LolaUSDCore__NonMatchingAdminAddress', type: 'error' },
  {
    inputs: [],
    name: 'LolaUSDCore__SpendApprovalFailedForAirdropContract',
    type: 'error',
  },
  { inputs: [], name: 'LolaUSDCore__ZeroAddressError', type: 'error' },
  { inputs: [], name: 'LolaUSD__AccessDenied_AdminOnly', type: 'error' },
  { inputs: [], name: 'LolaUSD__ExcessAllowanceDecrement', type: 'error' },
  {
    inputs: [],
    name: 'LolaUSD__ExcessSpendRequestOrUnauthorized',
    type: 'error',
  },
  { inputs: [], name: 'LolaUSD__InsufficientBalance', type: 'error' },
  { inputs: [], name: 'LolaUSD__InvalidProposalCodeName', type: 'error' },
  { inputs: [], name: 'LolaUSD__OperatorAddressIsZeroAddress', type: 'error' },
  { inputs: [], name: 'LolaUSD__OwnerAddressIsZeroAddress', type: 'error' },
  { inputs: [], name: 'LolaUSD__ProposalAlreadyExecuted', type: 'error' },
  { inputs: [], name: 'LolaUSD__ProposalIsNotBurnable', type: 'error' },
  { inputs: [], name: 'LolaUSD__ProposalIsNotMintable', type: 'error' },
  { inputs: [], name: 'LolaUSD__ReceiverAddressIsZeroAddress', type: 'error' },
  {
    inputs: [],
    name: 'LolaUSD__TransferOperationWasUnsuccessful',
    type: 'error',
  },
  {
    inputs: [],
    name: 'LolaUSD__UnsuccessfulTransferFromOperation',
    type: 'error',
  },
  { inputs: [], name: 'LolaUSD__ZeroAddressError', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_owner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_operator',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'string',
        name: 'message',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'string',
        name: 'contractName',
        type: 'string',
      },
    ],
    name: 'Logs',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: '_owner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: '_receiver',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_value',
        type: 'uint256',
      },
    ],
    name: 'Transfer',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_operator', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_operator', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_from', type: 'address' },
      { internalType: 'uint256', name: '_proposalId', type: 'uint256' },
      { internalType: 'string', name: '_proposalCodeName', type: 'string' },
    ],
    name: 'burn',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_operator', type: 'address' },
      { internalType: 'uint256', name: '_amountToDeduct', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAdminManagementCoreContractAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractName',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getProposalManagementCoreContractAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTokenLogo',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTokenMetadata',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_operator', type: 'address' },
      { internalType: 'uint256', name: '_amountToAdd', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_to', type: 'address' },
      { internalType: 'uint256', name: '_proposalId', type: 'uint256' },
      { internalType: 'string', name: '_proposalCodeName', type: 'string' },
    ],
    name: 'mint',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'ping',
    outputs: [
      { internalType: 'string', name: '', type: 'string' },
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_receiver', type: 'address' },
      { internalType: 'uint256', name: '_value', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newAddress', type: 'address' }],
    name: 'updateAdminManagementCoreContractAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newAddress', type: 'address' }],
    name: 'updateProposalManagementCoreContractAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'string', name: '_newLogoCID', type: 'string' }],
    name: 'updateTokenLogo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_newMetaDataCID', type: 'string' },
    ],
    name: 'updateTokenMetaData',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
